export const robots =[
    {
        id:1,
        name:'Tom',
        email:'tom@gmail.com'
    },
    {
        id:2,
        name:'jerry',
        email:'jerry@gmail.com'
    },
    {
        id:3,
        name:'nobita',
        email:'nobita@gmail.com'
    },
    {
        id:4,
        name:'sijuka',
        email:'sijuka@gmail.com'
    },
    {
        id:5,
        name:'jiyaan',
        email:'jiyaan@gmail.com'
    },
    {
        id:6,
        name:'donald',
        email:'donald@gmail.com'
    },
    {
        id:7,
        name:'pikachu',
        email:'pikachu@gmail.com'
    },
    {
        id:8,
        name:'mogli',
        email:'mogli@gmail.com'
    },
    {
        id:9,
        name:'chinchan',
        email:'chinchan@gmail.com'
    },
    {
        id:10,
        name:'chota bheem',
        email:'chotabheem@gmail.com'
    }
]